@startuml
'skinparam linetype polyline

!startsub MODEL
!includesub card.puml!CARDS
!includesub card.puml!FUNCTIONS
!includesub gamefield.puml!GAMEFIELD
!includesub game.puml!GAME
skinparam linetype ortho
skinparam nodesep 150
skinparam ranksep 100
Card <-[hidden]l- CardFactory
!endsub
@enduml