@startuml
'https://plantuml.com/class-diagram


interface Controller {}

class ServerController implements Controller {
    '- state : ServerState
    + setState(state : ServerState)
}

abstract class ServerState implements Controller {
    + transition()
}

ServerController --> ServerState : - state

abstract class LobbyState extends ServerState {
}

class GameChoiceState extends LobbyState{}
class GameJoinedState extends LobbyState{}

abstract class GameState extends ServerState{
}

class SetupState extends GameState {
}

class WaitState extends GameState {

}

class PlayState extends GameState {

}

class EndState extends GameState {

}



@enduml