skinparam dpi 300

@startuml
'https://plantuml.com/state-diagram

[*] --> Authentication
Authentication --> LobbyChoice : Successful authentication
Authentication --> Authentication : Error
LobbyChoice --> WaitingForStart : joinGame(id)
LobbyChoice --> WaitingForStart : createGame(info, etc...)
WaitingForStart --> GameSetup : gameStarted()
GameSetup --> WaitPhase : allPlayersHaveChosenSetup()
WaitPhase --> WaitPhase : currentPlayerChangedAndItIsNotYourTurn()
WaitPhase --> PlayPhase : isYourTurn()
PlayPhase --> RegisterGamePhase : movePerformed()
RegisterGamePhase --> WaitPhase : moveOnAfterSavingGameStatusToDisk()
WaitPhase : inactivePlayerSkipsTurn()
WaitPhase --> EndPhase : lastTurnPlayedByLastPlayer()
EndPhase --> LobbyChoice : userWantsToPlayAnotherGame()
LobbyChoice --> [*] : disconnect()

@enduml

## Events about which the controller and the player should be notified:

### Lobby events
- User joined created Lobby
- Another User joined the lobby where the client is present
- User disconnects
- User is disconnected / inactive
- Game ready to start / started

### Game events
- All players have chosen setup
- Current player has changed / Player performed move
- You are the current player
- Your turn has been skipped because of inactivity
- It is the last turn
- The game has ended