@startuml

' Only for server use
interface UserObserver {
    onStatusChange();
    onGameJoined();
    onDisconnection();
}

interface GameObserver {
    onAllPlayersHaveSetup();
    onCurrentPlayerChange();
    onPlayerMove();
    onGameEnded();
    onReachedLastTurn();
}

interface LobbyListObserver {
    onLobbyListUpdate();
}

interface LobbyObserver {
    onPlayerJoined();
    onPlayerExited();
    onLobbyDeleted(); /' Because no one is present '/
    onGameStarted();
}

@enduml