@startuml
skinparam linetype ortho
skinparam nodesep 150
skinparam ranksep 100
!startsub GAMEFIELD
class Point
{
    - x : int {readOnly}
    - y : int {readOnly}
    + Point(x : int, y : int)
    + x() : int
    + y() : int
    + toString() : String
    + equals(Object other) : boolean
    + hashCode() : long
    + sum(other : Point) : Point
    + sum(points : Point...) : Point {static}
    + sum(points : Collection<Point>) : Point {static}


}

note "Java record with extra sum() method" as N1
N1 .. Point

class GameField{
    - cards: Map<Point, Card>
    - angles: Map<Point, Symbol>
    - availableCells: Set<Point>
    - symbolCounters: Map<Symbol, int>

    + GameField(initialCard : Card)
    + getCards() : Map<Point, Card>
    + getAngles(): Map<Point, Symbol>
    + getCounter(symbol : Symbol) : int
    + addCard(card : Card, orientation : CardOrientation, position : Point)
    + getAvailablePositions() : Set<Point>
}
GameField .r..> Point : <<uses>>
!endsub



@enduml