@startuml

skinparam linetype ortho
skinparam ranksep 170
skinparam nodesep 120


[*] --> SetupGame
SetupGame: shuffleDecks()
SetupGame:generateRandomPickers()
SetupGame: putCardsOnTable()
SetupGame: choosePlayerOrder()


SetupGame --> SetupPlayers
SetupPlayers: cardsInHand()
SetupPlayers: chooseSecretObjective()
SetupPlayers: chooseInitialCardSide()
SetupPlayers: evaluateNextPlayer()


SetupPlayers --> MidGame
MidGame : PlayCard()
MidGame : UpdatePoints()
MidGame : DrawCard()
MidGame: evaluateNextPlayer()


MidGame --> PlayLastTurn : one of the players' scores is above 20 \nor the decks are empty
PlayLastTurn --> EvaluateScore
PlayLastTurn : PlayCard()
PlayLastTurn : UpdatePoints()
PlayLastTurn : DrawCard()
PlayLastTurn : evaluateLastPlayer()

EvaluateScore : findWinner()


@enduml