@startuml
skinparam nodesep 40
skinparam ranksep 30
!startsub GAMEFIELD
class Point
{
    - int x {readOnly}
    - int y {readOnly}
    + Point(x : int, y : int)
    + getX() : int
    + getY() : int
    + toString() : String
    + equals(Object other) : bool
    + hashCode() : int
    + sum(Point...) : Point
}

note "Java record with extra sum() method" as N1
N1 .. Point

class GameField{
    - cards: HashMap<Point, Card>
    - angles: HashMap<Point, Symbol>
    - availableCells: HashSet<Point>
    - symbolCounters: <Symbol, int>

    + GameField(initialCard : Card)
    + getCards() : HashMap<Point, Card>
    + getAngles(): HashMap<Point, Symbol>
    + getCounter(symbol : Symbol) : int
    + addCard(cardSide : CardSide, position : Point)
    + getAvailablePositions() : Set<Point>
}
GameField .r..> Point
!endsub



@enduml