@startuml
'skinparam linetype polyline

!startsub MODEL
!includesub card.puml!CARDS
!includesub card.puml!FUNCTIONS
!includesub gamefield.puml!GAMEFIELD
!includesub game.puml!GAME
Card <-[hidden]l- CardFactory
!endsub
@enduml